baseURL = 'https://kmaitreys.github.io/'
languageCode = 'en-us'
title = 'S. Maitrey'
enableGitInfo = true

[outputs]
home = ["HTML", "JSON", "RSS"]
section = ["HTML", "RSS"]
page = ["HTML"]

[frontmatter]
lastmod = [":git", "lastmod", "date", "publishDate"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
delimiters = { inline = [['$', '$'], ['\\(', '\\)']], block = [['$$', '$$'], ['\\[', '\\]']] }
[markup.highlight]
noClasses = false
style = "onedark"
[markup.tableOfContents]
endLevel = 4
startLevel = 2

[params]
name = "S. Maitrey"
title = "S. Maitrey"
description = "Graduate Student in Astronomy & Astrophysics. Planet Formation, Protoplanetary Disks, Astrochemistry, Exoplanets."
position = "PhD Student / Researcher"
affiliation = "The Kavli Institute for Astronomy and Astrophysics at Peking University"
affiliation_url = "https://kiaa.pku.edu.cn/"
research_area = "Planet Formation, Protoplanetary Disks, Astrochemistry, Exoplanets"
orcid = "0000-0003-3412-9454"
github = "kmaitreys"
scholar = "r5841owAAAAJ&hl"
email = "km.maitrey@gmail.com"
blog_url = "https://kmaitreys.github.io/blog/"
planeteslab_url = "https://planeteslab.github.io/"

[menu]
[[menu.main]]
name = "Main"
url = "/"
weight = 10
[[menu.main]]
name = "Research"
url = "/research/"
weight = 20
[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 30
[[menu.main]]
name = "Writing"
url = "/writing/"
weight = 40
[[menu.main]]
name = "Bio"
url = "/education/"
weight = 50
